import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./apigen"; // generated by openapi-typescript
import { API_BASE_URL } from "../api-base";

export const fetchClient = createFetchClient<paths>({
  baseUrl: API_BASE_URL,
});

export const $api = createClient(fetchClient);

export default $api;
